inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**
    - style/AsciiComments
Documentation:
    Enabled: false
Style/AsciiComments:
    Enabled: false